services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
# services:
#   db:
#     image: postgres:14.1-alpine
#     container_name: postgres
#     restart: always
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=vozra
#     ports:
#       - '54321:5432'
#     volumes:
#       - db:/var/lib/postgresql/data
#   pgadmin4:
#     container_name: pgadmin4
#     image: dpage/pgadmin4
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: ftopsx@gmail.com
#       PGADMIN_DEFAULT_PASSWORD: root
#     ports:
#       - '5050:80'
#     volumes:
#       - pgadmin4:/var/lib/pgadmin
# volumes:
#   db:
#   pgadmin4:

